# logLevel is the log level, if set only message with at least this level is logged
# e.g.: debug -> means error, warning, info and debug messages are logged
# Allowed values: debug | info | warning | error 
logLevel: info

# logDestination defines the log destinations.
#  supported values: stdout | stderr | /path/to/logfile
logDestination: stdout

# webserver configuration
webserver:
  # listenHost is the host address the https server listens for connections.
  listenHost: 0.0.0.0

  # listenPort is the port the https server listens for connections.
  listenPort: 443

  # aiKey is the global api key for the application.
  # empty means api key authentication is disabled.
  apiKey: 12345678

  # keyFile is the ssl certificate private key file
  keyFile: /opt/<MODULE>/etc/key.pem

  # CertFile is the ssl certificate public key file
  # Pfx files are supported as well, in which case KeyFile must be empty and CertFile must point to the pfx file, CertPassword must contain the password to decode the pfx file.
  certFile: /opt/<MODULE>/etc/cert.pem

  # BlockedIPs is a list of IP addresses or networks that are forbidden from accessing the application.
  # Default is empty, which means no IP addresses or networks are blocked.
  # Multiple IP addresses or networks can be defined separated by a comma
  # e.g.: 192.168.0.1,192.168.0.0/16,10.0.0.0/8,192.168.254.15
  blockedIPs: []
  #    - 192.168.0.1
  #    - 192.168.0.0/16
  #    - 10.0.0.0/8
  #    - 192.168.254.15

  # AllowedIPs is a list of IP addresses that are allowed to access the application.
  # Default is empty, which means all IP addresses are allowed.
  # The value "ALL" allows access from all IP Addresses / IP Networks
  # multiple IP addresses or networks can be defined separated by a comma
  # e.g.: 127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8
  # Note: '::1' is the IPv6 loopback address.
  allowedIPs: []
  #    - ALL
  #    - 127.0.0.1
  #    - ::1
  #    - 192.168.0.0/16
  #    - 10.0.0.0/8
