# logLevel is the log level, if set only message with at least this level is logged
# e.g.: debug -> means error, warning, info and debug messages are logged
# Allowed values: debug | info | warning | error | trace
# Default is info.
logLevel: info

# logDestination defines the log destinations.
#  supported values: stdout | stderr | /path/to/logfile
logDestination: stdout

# aiKey is the global api key for the application.
# apiKey must be encrypted with "app --crypt <plaintext>"
# Default is empty that means api key authentication is disabled.
# 12345678
apiKey: DOqIHra9dK1XJ/6Nx4/2vafH+cg36nXT8w1apl/wXhtIWdGI

# jwtSecret is a secret key used to sign jwt tokens.
# jwtSecret must be encrypted with "app --crypt <plaintext>"
# jwtSecret: encrypted

# jwtID is a unique identifier for the jwt token used to prevent login with the same jwt token to another app.
# jwtID: unique

# webserver configuration
webserver:
  # listenHost is the host address the https server listens for connections.
  # Default is empty, which means all available network interfaces.
  listenHost: 0.0.0.0

  # listenPort is the port the https server listens for connections.
  # Default is 443
  listenPort: 4000

  # minTLS is the minimum TLS version the server accepts.
  # Default is "1.2"
  minTLS: 1.2

  # keyFile is the ssl certificate private key file
  # Default is key.pem
  # keyFile:

  # CertFile is the ssl certificate public key file
  # Default is cert.pem
  # Pfx files are supported as well, in which case KeyFile must be empty and CertFile must point to the pfx file, CertPassword must contain the password to decode the pfx file.
  # certFile:

  # CertPassword is an optional certificate password that
  # CertPassword must be encrypted with "app --crypt <plaintext>"
  # Default is empty which means no password is used.
  # certPassword: encrypted

  # BlockedIPs is a list of IP addresses or networks that are forbidden from accessing the application.
  # Default is empty, which means no IP addresses or networks are blocked.
  # Multiple IP addresses or networks can be defined separated by a comma
  # e.g.: 192.168.0.1,192.168.0.0/16,10.0.0.0/8,192.168.254.15
  #  blockedIPs:
  #    - 192.168.0.1
  #    - 192.168.0.0/16
  #    - 10.0.0.0/8
  #    - 192.168.254.15

  # AllowedIPs is a list of IP addresses that are allowed to access the application.
  # Default is empty, which means all IP addresses are allowed.
  # The value "ALL" allows access from all IP Addresses / IP Networks
  # multiple IP addresses or networks can be defined separated by a comma
  # e.g.: 127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8
  # Note: '::1' is the IPv6 loopback address.
  #  allowedIPs:
  #    - ALL
  #    - 127.0.0.1
  #    - ::1
  #    - 192.168.0.0/16
  #    - 10.0.0.0/8
